// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pastes.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaste = `-- name: CreatePaste :one
insert into pastes
(reference, owner, title, content, syntax, tags, expiration, public, password)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
returning id
`

type CreatePasteParams struct {
	Reference  string           `db:"reference" json:"reference"`
	Owner      pgtype.Text      `db:"owner" json:"owner"`
	Title      string           `db:"title" json:"title"`
	Content    string           `db:"content" json:"content"`
	Syntax     pgtype.Text      `db:"syntax" json:"syntax"`
	Tags       []string         `db:"tags" json:"tags"`
	Expiration pgtype.Timestamp `db:"expiration" json:"expiration"`
	Public     bool             `db:"public" json:"public"`
	Password   pgtype.Text      `db:"password" json:"password"`
}

// CreatePaste
//
//	insert into pastes
//	(reference, owner, title, content, syntax, tags, expiration, public, password)
//	values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
//	returning id
func (q *Queries) CreatePaste(ctx context.Context, arg CreatePasteParams) (int64, error) {
	row := q.db.QueryRow(ctx, createPaste,
		arg.Reference,
		arg.Owner,
		arg.Title,
		arg.Content,
		arg.Syntax,
		arg.Tags,
		arg.Expiration,
		arg.Public,
		arg.Password,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteExpiredPastes = `-- name: DeleteExpiredPastes :many
update pastes
set deleted_at = now()
where expiration < now() and deleted_at is null
returning reference
`

// DeleteExpiredPastes
//
//	update pastes
//	set deleted_at = now()
//	where expiration < now() and deleted_at is null
//	returning reference
func (q *Queries) DeleteExpiredPastes(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteExpiredPastes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var reference string
		if err := rows.Scan(&reference); err != nil {
			return nil, err
		}
		items = append(items, reference)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePaste = `-- name: DeletePaste :exec
update pastes
set deleted_at = now()
where reference = $1
    and deleted_at is null
`

// DeletePaste
//
//	update pastes
//	set deleted_at = now()
//	where reference = $1
//	    and deleted_at is null
func (q *Queries) DeletePaste(ctx context.Context, reference string) error {
	_, err := q.db.Exec(ctx, deletePaste, reference)
	return err
}

const getPasteByID = `-- name: GetPasteByID :one
select id, reference, title, content, syntax, tags, expiration, public, created_at, updated_at, deleted_at, views, password, owner
from pastes
where id = $1
    and deleted_at is null
`

// GetPasteByID
//
//	select id, reference, title, content, syntax, tags, expiration, public, created_at, updated_at, deleted_at, views, password, owner
//	from pastes
//	where id = $1
//	    and deleted_at is null
func (q *Queries) GetPasteByID(ctx context.Context, id int64) (Paste, error) {
	row := q.db.QueryRow(ctx, getPasteByID, id)
	var i Paste
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.Title,
		&i.Content,
		&i.Syntax,
		&i.Tags,
		&i.Expiration,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Views,
		&i.Password,
		&i.Owner,
	)
	return i, err
}

const getPasteByReference = `-- name: GetPasteByReference :one
update pastes
set views = views + 1
where reference = $1
    and deleted_at is null
returning id, reference, title, content, syntax, tags, expiration, public, created_at, updated_at, deleted_at, views, password, owner
`

// GetPasteByReference
//
//	update pastes
//	set views = views + 1
//	where reference = $1
//	    and deleted_at is null
//	returning id, reference, title, content, syntax, tags, expiration, public, created_at, updated_at, deleted_at, views, password, owner
func (q *Queries) GetPasteByReference(ctx context.Context, reference string) (Paste, error) {
	row := q.db.QueryRow(ctx, getPasteByReference, reference)
	var i Paste
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.Title,
		&i.Content,
		&i.Syntax,
		&i.Tags,
		&i.Expiration,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Views,
		&i.Password,
		&i.Owner,
	)
	return i, err
}

const listPublicPastes = `-- name: ListPublicPastes :many
select id, reference, title, content, syntax, tags, expiration, public, created_at, updated_at, deleted_at, views, password, owner
from pastes
where public = true
    and deleted_at is null
order by created_at desc
`

// ListPublicPastes
//
//	select id, reference, title, content, syntax, tags, expiration, public, created_at, updated_at, deleted_at, views, password, owner
//	from pastes
//	where public = true
//	    and deleted_at is null
//	order by created_at desc
func (q *Queries) ListPublicPastes(ctx context.Context) ([]Paste, error) {
	rows, err := q.db.Query(ctx, listPublicPastes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Paste
	for rows.Next() {
		var i Paste
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.Title,
			&i.Content,
			&i.Syntax,
			&i.Tags,
			&i.Expiration,
			&i.Public,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Views,
			&i.Password,
			&i.Owner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPastes = `-- name: ListUserPastes :many
select id, reference, title, content, syntax, tags, expiration, public, created_at, updated_at, deleted_at, views, password, owner
from pastes
where owner = $1
    and deleted_at is null
order by created_at desc
`

// ListUserPastes
//
//	select id, reference, title, content, syntax, tags, expiration, public, created_at, updated_at, deleted_at, views, password, owner
//	from pastes
//	where owner = $1
//	    and deleted_at is null
//	order by created_at desc
func (q *Queries) ListUserPastes(ctx context.Context, owner pgtype.Text) ([]Paste, error) {
	rows, err := q.db.Query(ctx, listUserPastes, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Paste
	for rows.Next() {
		var i Paste
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.Title,
			&i.Content,
			&i.Syntax,
			&i.Tags,
			&i.Expiration,
			&i.Public,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Views,
			&i.Password,
			&i.Owner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
