// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
insert into sessions
(token, username, data, expires_at)
values ($1, $2, $3, $4)
returning id, token, username, data, created_at, expires_at
`

type CreateSessionParams struct {
	Token     pgtype.UUID      `db:"token" json:"token"`
	Username  string           `db:"username" json:"username"`
	Data      []byte           `db:"data" json:"data"`
	ExpiresAt pgtype.Timestamp `db:"expires_at" json:"expires_at"`
}

// CreateSession
//
//	insert into sessions
//	(token, username, data, expires_at)
//	values ($1, $2, $3, $4)
//	returning id, token, username, data, created_at, expires_at
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.Token,
		arg.Username,
		arg.Data,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Username,
		&i.Data,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
delete from sessions
where expires_at <= now()
`

// DeleteExpiredSessions
//
//	delete from sessions
//	where expires_at <= now()
func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
delete from sessions
where token = $1
`

// DeleteSession
//
//	delete from sessions
//	where token = $1
func (q *Queries) DeleteSession(ctx context.Context, token pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
select id, token, username, data, created_at, expires_at
from sessions
where token = $1
    and expires_at > now()
`

// GetSessionByToken
//
//	select id, token, username, data, created_at, expires_at
//	from sessions
//	where token = $1
//	    and expires_at > now()
func (q *Queries) GetSessionByToken(ctx context.Context, token pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, token)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Username,
		&i.Data,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
