// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
insert into users
(username, uuid, credentials)
values ($1, $2, $3)
returning id, username, uuid, credentials, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Username    string      `db:"username" json:"username"`
	Uuid        pgtype.UUID `db:"uuid" json:"uuid"`
	Credentials []byte      `db:"credentials" json:"credentials"`
}

// CreateUser
//
//	insert into users
//	(username, uuid, credentials)
//	values ($1, $2, $3)
//	returning id, username, uuid, credentials, created_at, updated_at, deleted_at
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Uuid, arg.Credentials)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Uuid,
		&i.Credentials,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
update users
set deleted_at = now()
where id = $1
`

// DeleteUser
//
//	update users
//	set deleted_at = now()
//	where id = $1
func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByUsername = `-- name: GetUserByUsername :one
select id, username, uuid, credentials, created_at, updated_at, deleted_at
from users
where username = $1
    and deleted_at is null
`

// GetUserByUsername
//
//	select id, username, uuid, credentials, created_at, updated_at, deleted_at
//	from users
//	where username = $1
//	    and deleted_at is null
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Uuid,
		&i.Credentials,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserCredentials = `-- name: UpdateUserCredentials :exec
update users
set credentials = $2
where username = $1
`

type UpdateUserCredentialsParams struct {
	Username    string `db:"username" json:"username"`
	Credentials []byte `db:"credentials" json:"credentials"`
}

// UpdateUserCredentials
//
//	update users
//	set credentials = $2
//	where username = $1
func (q *Queries) UpdateUserCredentials(ctx context.Context, arg UpdateUserCredentialsParams) error {
	_, err := q.db.Exec(ctx, updateUserCredentials, arg.Username, arg.Credentials)
	return err
}
