apiVersion: 1

deleteDatasources:
  - name: Mimir
  - name: Tempo
  - name: Loki

datasources:
  - name: Mimir
    type: prometheus
    uid: mimir
    access: proxy
    url: http://localhost:4100/prometheus
    isDefault: true
    jsonData:
      httpMethod: POST
      prometheusType: "Mimir"
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
      tlsSkipVerify: true
      timeInterval: "5s"

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://localhost:4200
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: 'mimir'

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://localhost:4300
    jsonData:
      maxLines: 1000
      derivedFields:
        # Service Information
        - name: service
          matcherRegex: resources_service_name=["']?(.*?)["']?[, }]
          url: ""
        - name: environment
          matcherRegex: resources_deployment_environment=["']?(.*?)["']?[, }]
          url: ""
        # HTTP Request Information
        - name: method
          matcherRegex: attributes_method=["']?(.*?)["']?[, }]
          url: ""
        - name: status
          matcherRegex: attributes_status=["']?(.*?)["']?[, }]
          url: ""
        - name: url
          matcherRegex: attributes_url=["']?(.*?)["']?[, }]
          url: ""
        # Trace Information
        - name: trace_id
          matcherRegex: attributes_trace_id=["']?(.*?)["']?[, }]
          url: ${__value.raw}
          datasourceUid: tempo
