server:
  http_listen_port: 4200
  grpc_listen_port: 9200

distributor:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: "0.0.0.0:4250"

storage:
  trace:
    backend: local
    local:
      path: ./data/tempo/traces
    wal:
      path: ./data/tempo/wal

ingester:
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 1h

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: local
