package attributes

import (
	"fmt"

	"go.opentelemetry.io/otel/attribute"
)

// Bool creates a KeyValue with a BOOL Value type.
func Bool(key string, value bool) attribute.KeyValue {
	return attribute.Bool(key, value)
}

// BoolSlice creates a KeyValue with a BOOLSLICE Value type.
func BoolSlice(key string, values []bool) attribute.KeyValue {
	return attribute.BoolSlice(key, values)
}

// Int creates a KeyValue with an INT64 Value type.
func Int(key string, value int) attribute.KeyValue {
	return attribute.Int(key, value)
}

// IntSlice creates a KeyValue with an INT64SLICE Value type.
func IntSlice(key string, values []int) attribute.KeyValue {
	return attribute.IntSlice(key, values)
}

// Int64 creates a KeyValue with an INT64 Value type.
func Int64(key string, value int64) attribute.KeyValue {
	return attribute.Int64(key, value)
}

// Int64Slice creates a KeyValue with an INT64SLICE Value type.
func Int64Slice(key string, values []int64) attribute.KeyValue {
	return attribute.Int64Slice(key, values)
}

// Float64 creates a KeyValue with a FLOAT64 Value type.
func Float64(key string, value float64) attribute.KeyValue {
	return attribute.Float64(key, value)
}

// Float64Slice creates a KeyValue with a FLOAT64SLICE Value type.
func Float64Slice(key string, values []float64) attribute.KeyValue {
	return attribute.Float64Slice(key, values)
}

// String creates a KeyValue with a STRING Value type.
func String(key, value string) attribute.KeyValue {
	return attribute.String(key, value)
}

// StringSlice creates a KeyValue with a STRINGSLICE Value type.
func StringSlice(key string, values []string) attribute.KeyValue {
	return attribute.StringSlice(key, values)
}

// Stringer creates a new key-value pair with a passed name and a string
// value generated by the passed Stringer interface.
func Stringer(key string, value fmt.Stringer) attribute.KeyValue {
	return attribute.Stringer(key, value)
}
